# inter.pyi
from typing import Callable

def set_keyboard(device_id: str) -> None: ...
def set_mouse(device_id: str) -> None: ...
def set_keyboard_wait() -> None: ...
def set_mouse_wait() -> None: ...
def mouse_move(x_amount: int, y_amount: int) -> None: ...
def mouse_move_coord(x_location: int, y_location: int) -> None: ...
def send_key(key_code: int) -> None: ...
def send_key_state(key_code: int, state: bool) -> None: ...
def send_button(button_code: int) -> None: ...
def send_button_state(button_code: int, state: bool) -> None: ...
def get_key_state(key_code: int) -> bool: ...
def get_button_state(button_code: int) -> bool: ...
def sub_key(code: int, cb: Callable[[int], None], block: bool) -> None: ...
def un_sub_key(code: int) -> None: ...
def sub_button(btn: int, cb: Callable[[int], None], block: bool) -> None: ...
def un_sub_button(btn: int) -> None: ...
def sub_mouse_move(cb: Callable[[int, int], None], block: bool) -> None: ...
def un_sub_mouse_move() -> None: ...
def sub_mouse_move_amount(cb: Callable[[], None], x: int, y: int, block: bool) -> None: ...
def un_sub_mouse_move_amount() -> None: ...
def sub_mouse_move_coord(cb: Callable[[], None], x1: int, y1: int, x2: int, y2: int, block: bool) -> None: ...
def un_sub_mouse_move_coord() -> None: ...